name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none # default is xdebug
          extensions: mbstring, uuid # needed by phpunit

      - run: composer install --dev --no-progress

  ecs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - run: composer install --dev --no-progress
      - run: composer run-script check-cs

  rector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - run: composer install --dev --no-progress
      - run: composer run-script rector-dry

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none # default is xdebug

      - run: composer install --dev --no-progress
      - run: composer run-script ps
